import Footer from "@/components/custom/footer";
import Navbar from "@/components/custom/navbar";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./blog.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Suresh | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className + " max-w-2xl px-2 mx-auto"}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
